<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

use function Ramsey\Uuid\v1;

class BuildingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
       $data = [
        [
           'building_age' => '1965',
           'wood_price' => '16.8',
           'src_price' => '45.0',
           'rc_price' => '30.3',
           'sc_price' => '17.9',
           'lgs_price' => '16.8',
         ],
        [
           'building_age' => '1966',
           'wood_price' => '18.2',
           'src_price' => '42.4',
           'rc_price' => '30.6',
           'sc_price' => '17.8',
           'lgs_price' => '18.2',
         ],
        [
           'building_age' => '1967',
           'wood_price' => '19.9',
           'src_price' => '43.6',
           'rc_price' => '33.7',
           'sc_price' => '19.6',
           'lgs_price' => '19.9',
         ],
          [
           'building_age' => '1968',
           'wood_price' => '22.2',
           'src_price' => '48.6',
           'rc_price' => '36.2',
           'sc_price' => '21.7',
           'lgs_price' => '22.2',
         ],
          [
           'building_age' => '1969',
           'wood_price' => '24.9',
           'src_price' => '50.9',
           'rc_price' => '39.0',
           'sc_price' => '23.6',
           'lgs_price' => '24.9',
       ],
          [
           'building_age' => '1970',
           'wood_price' => '28.0',
           'src_price' => '54.3',
           'rc_price' => '42.9',
           'sc_price' => '26.1',
           'lgs_price' => '28.0',
         ],
        [
           'building_age' => '1971',
           'wood_price' => '31.2',
           'src_price' => '61.2',
           'rc_price' => '30.3',
           'sc_price' => '47.2',
           'lgs_price' => '31.2',
          ],
          [
           'building_age' => '1972',
           'wood_price' => '34.2',
           'src_price' => '61.6',
           'rc_price' => '50.2',
           'sc_price' => '47.2',
           'lgs_price' => '34.2',
       ],
       [
           'building_age' => '1973',
           'wood_price' => '45.3',
           'src_price' => '77.6',
           'rc_price' => '64.3',
           'sc_price' => '42.2',
           'lgs_price' => '45.3',
       ],
        [
           'building_age' => '1974',
           'wood_price' => '61.8',
           'src_price' => '113.0',
           'rc_price' => '90.1',
           'sc_price' => '55.7',
           'lgs_price' => '61.8',
       ],
       [
           'building_age' => '1975',
           'wood_price' => '67.7',
           'src_price' => '126.4',
           'rc_price' => '97.4',
           'sc_price' => '60.5',
           'lgs_price' => '67.7',
       ],
       [
           'building_age' => '1976',
           'wood_price' => '70.3',
           'src_price' => '114.6',
           'rc_price' => '98.2',
           'sc_price' => '62.1',
           'lgs_price' => '70.3',
       ],
       [
           'building_age' => '1977',
           'wood_price' => '74.1',
           'src_price' => '121.8',
           'rc_price' => '102.0',
           'sc_price' => '65.3',
           'lgs_price' => '74.1',
       ],
       [
           'building_age' => '1978',
           'wood_price' => '77.9',
           'src_price' => '122.4',
           'rc_price' => '105.9',
           'sc_price' => '70.1',
           'lgs_price' => '77.9',
       ],
       [
           'building_age' => '1979',
           'wood_price' => '82.5',
           'src_price' => '128.9',
           'rc_price' => '114.3',
           'sc_price' => '75.4',
           'lgs_price' => '82.5',
       ],
       [
           'building_age' => '1980',
           'wood_price' => '92.5',
           'src_price' => '149.4',
           'rc_price' => '129.7',
           'sc_price' => '84.1',
           'lgs_price' => '92.5',
       ],
       [
           'building_age' => '1981',
           'wood_price' => '98.3',
           'src_price' => '161.8',
           'rc_price' => '138.7',
           'sc_price' => '91.7',
           'lgs_price' => '98.3',
       ],
       [
           'building_age' => '1982',
           'wood_price' => '101.3',
           'src_price' => '170.9',
           'rc_price' => '143.0',
           'sc_price' => '93.9',
           'lgs_price' => '101.3',
       ],
       [
           'building_age' => '1983',
           'wood_price' => '102.2',
           'src_price' => '168.0',
           'rc_price' => '143.8',
           'sc_price' => '94.3',
           'lgs_price' => '102.2',
       ],
       [
           'building_age' => '1984',
           'wood_price' => '102.8',
           'src_price' => '161.2',
           'rc_price' => '141.7',
           'sc_price' => '95.3',
           'lgs_price' => '102.8',
       ],
       [
           'building_age' => '1985',
           'wood_price' => '104.2',
           'src_price' => '172.2',
           'rc_price' => '144.5',
           'sc_price' => '96.9',
           'lgs_price' => '104.2',
       ],
       [
           'building_age' => '1986',
           'wood_price' => '106.2',
           'src_price' => '181.9',
           'rc_price' => '149.5',
           'sc_price' => '102.6',
           'lgs_price' => '106.2',
       ],
       [
           'building_age' => '1987',
           'wood_price' => '110.0',
           'src_price' => '191.8',
           'rc_price' => '156.6',
           'sc_price' => '108.4',
           'lgs_price' => '110.0',
       ],
       [
           'building_age' => '1988',
           'wood_price' => '116.5',
           'src_price' => '203.6',
           'rc_price' => '175.0',
           'sc_price' => '117.3',
           'lgs_price' => '116.5',
       ],
       [
           'building_age' => '1989',
           'wood_price' => '123.1',
           'src_price' => '237.3',
           'rc_price' => '193.3',
           'sc_price' => '128.4',
           'lgs_price' => '123.1',
       ],
       [
           'building_age' => '1990',
           'wood_price' => '131.7',
           'src_price' => '286.7',
           'rc_price' => '222.9',
           'sc_price' => '147.4',
           'lgs_price' => '131.7',
       ],
       [
           'building_age' => '1991',
           'wood_price' => '137.6',
           'src_price' => '329.8',
           'rc_price' => '246.8',
           'sc_price' => '158.7',
           'lgs_price' => '137.6',
       ],
       [
           'building_age' => '1992',
           'wood_price' => '143.5',
           'src_price' => '333.7',
           'rc_price' => '245.6',
           'sc_price' => '162.4',
           'lgs_price' => '143.5',
       ],
       [
           'building_age' => '1993',
           'wood_price' => '150.9',
           'src_price' => '300.3',
           'rc_price' => '227.5',
           'sc_price' => '159.2',
           'lgs_price' => '150.9',
       ],
       [
           'building_age' => '1994',
           'wood_price' => '156.6',
           'src_price' => '262.9',
           'rc_price' => '212.8',
           'sc_price' => '148.4',
           'lgs_price' => '156.6',
       ],
       [
           'building_age' => '1995',
           'wood_price' => '158.3',
           'src_price' => '228.8',
           'rc_price' => '199.0',
           'sc_price' => '143.2',
           'lgs_price' => '158.3',
       ],
       [
           'building_age' => '1996',
           'wood_price' => '161.0',
           'src_price' => '229.7',
           'rc_price' => '198.0',
           'sc_price' => '143.6',
           'lgs_price' => '161.0',
       ],
       [
           'building_age' => '1997',
           'wood_price' => '160.5',
           'src_price' => '223.0',
           'rc_price' => '201.0',
           'sc_price' => '141.0',
           'lgs_price' => '160.5',
       ],
       [
           'building_age' => '1998',
           'wood_price' => '158.6',
           'src_price' => '225.6',
           'rc_price' => '203.8',
           'sc_price' => '138.7',
           'lgs_price' => '158.6',
       ],
       [
           'building_age' => '1999',
           'wood_price' => '159.3',
           'src_price' => '220.9',
           'rc_price' => '197.9',
           'sc_price' => '139.4',
           'lgs_price' => '159.3',
       ],
       [
           'building_age' => '2000',
           'wood_price' => '159.0',
           'src_price' => '204.3',
           'rc_price' => '182.6',
           'sc_price' => '132.3',
           'lgs_price' => '159.0',
       ],
       [
           'building_age' => '2001',
           'wood_price' => '157.2',
           'src_price' => '186.1',
           'rc_price' => '177.8',
           'sc_price' => '136.4',
           'lgs_price' => '157.2',
       ],
       [
           'building_age' => '2002',
           'wood_price' => '153.6',
           'src_price' => '195.2',
           'rc_price' => '180.5',
           'sc_price' => '135.0',
           'lgs_price' => '153.6',
       ],
       [
           'building_age' => '2003',
           'wood_price' => '152.7',
           'src_price' => '187.3',
           'rc_price' => '179.5',
           'sc_price' => '131.4',
           'lgs_price' => '152.7',
       ],
       [
           'building_age' => '2004',
           'wood_price' => '152.1',
           'src_price' => '190.1',
           'rc_price' => '176.1',
           'sc_price' => '130.6',
           'lgs_price' => '152.1',
       ],
       [
           'building_age' => '2005',
           'wood_price' => '151.9',
           'src_price' => '185.7',
           'rc_price' => '171.5',
           'sc_price' => '132.8',
           'lgs_price' => '151.9',
       ],
       [
           'building_age' => '2006',
           'wood_price' => '152.9',
           'src_price' => '170.5',
           'rc_price' => '178.6',
           'sc_price' => '133.7',
           'lgs_price' => '152.9',
       ],
       [
           'building_age' => '2007',
           'wood_price' => '153.6',
           'src_price' => '182.5',
           'rc_price' => '185.8',
           'sc_price' => '135.6',
           'lgs_price' => '153.6',
       ],
       [
           'building_age' => '2008',
           'wood_price' => '156.0',
           'src_price' => '229.1',
           'rc_price' => '206.1',
           'sc_price' => '158.3',
           'lgs_price' => '156.0',
       ],
       [
           'building_age' => '2009',
           'wood_price' => '156.6',
           'src_price' => '265.2',
           'rc_price' => '219.0',
           'sc_price' => '169.5',
           'lgs_price' => '156.6',
       ],
       [
           'building_age' => '2010',
           'wood_price' => '156.5',
           'src_price' => '226.4',
           'rc_price' => '205.9',
           'sc_price' => '163.0',
           'lgs_price' => '156.5',
       ],
       [
           'building_age' => '2011',
           'wood_price' => '156.8',
           'src_price' => '238.4',
           'rc_price' => '197.0',
           'sc_price' => '158.9',
           'lgs_price' => '156.8',
       ],
       [
           'building_age' => '2012',
           'wood_price' => '157.6',
           'src_price' => '223.3',
           'rc_price' => '193.9',
           'sc_price' => '155.6',
           'lgs_price' => '157.6',
       ],
       [
           'building_age' => '2013',
           'wood_price' => '159.9',
           'src_price' => '258.5',
           'rc_price' => '203.8',
           'sc_price' => '164.3',
           'lgs_price' => '159.9',
       ],
       [
           'building_age' => '2014',
           'wood_price' => '163.0',
           'src_price' => '276.2',
           'rc_price' => '228.0',
           'sc_price' => '176.4',
           'lgs_price' => '163.0',
       ],
       [
           'building_age' => '2015',
           'wood_price' => '165.4',
           'src_price' => '262.2',
           'rc_price' => '240.2',
           'sc_price' => '197.3',
           'lgs_price' => '165.4',
       ],
       [
           'building_age' => '2016',
           'wood_price' => '165.9',
           'src_price' => '308.3',
           'rc_price' => '254.2',
           'sc_price' => '204.1',
           'lgs_price' => '165.9',
       ],
       [
           'building_age' => '2017',
           'wood_price' => '166.7',
           'src_price' => '350.4',
           'rc_price' => '265.5',
           'sc_price' => '214.6',
           'lgs_price' => '166.7',
       ],
       [
           'building_age' => '2018',
           'wood_price' => '168.5',
           'src_price' => '304.2',
           'rc_price' => '263.1',
           'sc_price' => '214.1',
           'lgs_price' => '168.5',
       ],
       [
           'building_age' => '2019',
           'wood_price' => '170.1',
           'src_price' => '369.3',
           'rc_price' => '285.6',
           'sc_price' => '228.8',
           'lgs_price' => '170.1',
       ],
       [
           'building_age' => '2020',
           'wood_price' => '172.0',
           'src_price' => '279.2',
           'rc_price' => '277.0',
           'sc_price' => '230.2',
           'lgs_price' => '172.0',
       ],
       [
           'building_age' => '2021',
           'wood_price' => '172.2',
           'src_price' => '338.4',
           'rc_price' => '288.3',
           'sc_price' => '227.3',
           'lgs_price' => '241.5',
       ],
       [
           'building_age' => '2022',
           'wood_price' => '176.2',
           'src_price' => '434.4',
           'rc_price' => '277.5',
           'sc_price' => '241.5',
           'lgs_price' => '176.2',
       ],
    //    [
    //        'building_age' => '2023',
    //        'wood_price' => '',
    //        'src_price' => '',
    //        'rc_price' => '',
    //        'sc_price' => '',
    //        'lgs_price' => '',
    //    ],
    //    [
    //        'building_age' => '2024',
    //        'wood_price' => '',
    //        'src_price' => '',
    //        'rc_price' => '',
    //        'sc_price' => '',
    //        'lgs_price' => '',
    //    ],
   ];

   DB::table('buildings')->insert($data);
}
}
